std = "lua51"
codes = true
max_line_length = 120
ignore = {
  "611",
  "631",
}

read_globals = {
  "C_Timer",
  "CreateFrame",
  "DEFAULT_CHAT_FRAME",
  "GameTooltip",
  "GetCursorPosition",
  "GetHonorCurrency",
  "GetLifetimeHonorableKills",
  "GetMaxHonorCurrency",
  "GetMinimapShape",
  "GetMoney",
  "GetPVPLifetimeStats",
  "GetRealmName",
  "GetTime",
  "GetZoneText",
  "InCombatLockdown",
  "IsInInstance",
  "Minimap",
  "RegisterStateDriver",
  "UIParent",
  "UISpecialFrames",
  "UnitClass",
  "UnitLevel",
  "UnitName",
  "UnitXP",
  "UnitXPMax",
  "UnregisterStateDriver",
  "tinsert",
}

globals = {
  "DingTimerDB",
  "DingTimerMainWindow",
  "DingTimerMinimapButton",
  "DingTimerSettingsPanel",
  "DingTimerStatsPanel",
  "DingTimerXPGraphPanel",
  "SLASH_DINGTIMER1",
  "SLASH_DINGTIMER2",
  "SlashCmdList",
}

files["tests/test_*.lua"] = {
  max_line_length = false,
  globals = {
    "C_Timer",
    "ClearChatLog",
    "CreateFrame",
    "DingTimerDB",
    "DingTimerMainWindow",
    "DingTimerMinimapButton",
    "DingTimerSettingsPanel",
    "DingTimerXPGraphPanel",
    "DingTimerStatsPanel",
    "GetChatLog",
    "GetHonorCurrency",
    "GetMaxHonorCurrency",
    "GetTime",
    "InCombatLockdown",
    "LoadAddonFile",
    "NS",
    "RegisterStateDriver",
    "SetHonor",
    "SetInstanceState",
    "SetLevel",
    "SetLifetimeHKs",
    "SetMoney",
    "SetProfileIdentity",
    "SetTime",
    "SetXP",
    "SetZone",
    "SlashCmdList",
    "UIParent",
    "assertEqual",
    "assertStringMatch",
    "assert_eq",
    "assert_equal",
    "assert_false",
    "assert_near",
    "assert_true",
    "it",
    "run_tests",
  },
}

files["tests/mocks.lua"] = {
  globals = {
    "C_Timer",
    "ClearChatLog",
    "CreateFrame",
    "DEFAULT_CHAT_FRAME",
    "DEFAULT_CHAT_LOG",
    "GameTooltip",
    "GetChatLog",
    "GetCursorPosition",
    "GetHonorCurrency",
    "GetLifetimeHonorableKills",
    "GetMaxHonorCurrency",
    "GetMinimapShape",
    "GetMoney",
    "GetPVPLifetimeStats",
    "GetRealmName",
    "GetTime",
    "GetZoneText",
    "InCombatLockdown",
    "IsInInstance",
    "LoadAddonFile",
    "Minimap",
    "RegisterStateDriver",
    "SetHonor",
    "SetInstanceState",
    "SetLevel",
    "SetLifetimeHKs",
    "SetMoney",
    "SetProfileIdentity",
    "SetTime",
    "SetXP",
    "SetZone",
    "SlashCmdList",
    "UIParent",
    "UISpecialFrames",
    "UnitClass",
    "UnitLevel",
    "UnitName",
    "UnitXP",
    "UnitXPMax",
    "UnregisterStateDriver",
    "assertEqual",
    "assertStringMatch",
    "assert_eq",
    "assert_equal",
    "assert_false",
    "assert_near",
    "assert_true",
    "it",
    "run_tests",
    "tinsert",
  },
}

files["benchmark_*.lua"] = {
  ignore = {
    "211",
    "212",
    "213",
    "241",
  },
}
